version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    executor:
      name: node/default
      tag: '16.14'
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
  release:
    executor:
      name: node/default
      tag: '16.14'
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn pkg
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./dist/artifacts
      - run:
          name: "Publish Release on GitHub"
          filters:
            tags:
              only: /^v.*/
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./dist/artifacts/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /^main/
  release:
    jobs:
      - build:
          filters:
            branches:
              only: /^main/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - publish-github-release:
          requires:
            - release
          filters:
            tags:
              only: /^v.*/



