version: 2.1
orbs:
  node: circleci/node@4.7.0
  gh: circleci/github-cli@1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '16.14'
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  release:
    executor:
      name: node/default
      tag: '16.14'
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn pkg
      - persist_to_workspace:
          root: .
          paths:
          - ./dist/artifacts
  upload:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - gh/setup
      - run: gh release upload --repo "$(git config --get remote.origin.url)" ${CIRCLE_TAG} /tmp/dist/artifacts/**

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - release:
          filters:
            tags:
              only: /^v.*/
      - upload:
          pre-steps:
            - attach_workspace:
                at: /tmp
          requires:
            - release
          filters:
            tags:
              only: /^v.*/



